apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30030
  selector:
    app.kubernetes.io/name: grafana
  type: NodePort
