apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: kubernetes-manifests/prod
    repoURL: https://github.com/ualali/udacity-shop
    targetRevision: HEAD
